<a href="https://colab.research.google.com/github/carlosramos1/numpy-pandas-matplotlib/blob/main/PD01_introduccion_a_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción a *Pandas*.

El proyecto [*Pandas*](https://pandas.pydata.org/) es una herramienta especializada en la gestión de "series" y "dataframes".

- Las "series" son arreglos de datos de una dimensión
- Los "dataframes" son arreglos de datos de dos dimensiones.

In [ ]:
# por convención se nombra 'pd'
import pandas as pd
pd.__version__

'2.2.2'

In [ ]:
import numpy as np
np.__version__

'2.0.2'

## Los *dataframes*.

Los dataframes de *Pandas* **se basan en arreglos de datos de 2 dimensiones** compuesto por columnas y filas.

### Creación de *Dataframes*.

La clase ```pandas.DataFrame``` se utiliza para crear los dataframes de *Pandas*.

```
pd.DataFrame(<datos>)
```

Donde:

* ```<datos>``` puede ser un objeto tipo:
  * `list` que contiene listas.
  * ```tuple``` que contiene  a otros objetos tipo ```tuple```.
  * ```numpy.ndarray``` de 2 dimensiones.
  * ```dict```.
  * Otra instancia de  ```pd.DataFrame```.



https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html

**Ejemplo:**

In [ ]:
# Crear un dataframe a partir de una 'tupla'
pd.DataFrame( ((5, 1, 2), (2, 3, 4)) )

   0  1  2
0  5  1  2
1  2  3  4

In [ ]:
# Crear un dataframe a partir de un 'array de numpy'
matriz = np.arange(9).reshape(3, 3)
pd.DataFrame(matriz)

   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [ ]:
# Crear un dataframe a partir de un 'diccionario'
data = {'Nombre': ['Juan', 'Ana', 'Jose', 'Tito'],
        'Edad':   [25, 18, 23, 27],
        'Pais':   ['BO', 'CO', 'AR', 'BO']}

pd.DataFrame(data)
# Las claves del diccionario, serán los identificadores de columna

  Nombre  Edad Pais
0   Juan    25   BO
1    Ana    18   CO
2   Jose    23   AR
3   Tito    27   BO

#### Índices en un dataframe.

De manera similar a un arreglo, los dataframes tienen indices tanto para identificar filas como para identificar columnas.

Los índices pueden ser:
 - Números enteros (`int`), entre `0` y `length-1` del eje.
 - Cadenas de texto (`str`).

Los indices se pueden definir al momento de la creación del dataframe, a través de los parametros `index=` y `columns=`. **Si no se estable** estos parámetros, los indices ***por defecto son números***


```
pd.DataFrame(<datos>, index=<id-fila>, columns=<id-columna>)
```
* ```<id-fila>``` es un objeto iterable de strings (p.e. una lista), el cual contiene los **identificadore de cada fila**.
* ```<id-columna>``` es un objeto iterable de strings (p.e. una lista), el cual contiene los **identificadore de cada columna**.

**Ejemplos:**

In [ ]:
# Crear un dataframe estableciendo indices de renglon e indices de columna
pd.DataFrame( [[1,2,3],[4,5,6],[7,8,9]],
              index=['uno','dos','tres'],
              columns=['a', 'b', 'c'])

      a  b  c
uno   1  2  3
dos   4  5  6
tres  7  8  9

In [ ]:
# Crear un dataframe estableciendo solo indices de columna
pd.DataFrame( [[1,2,3],[4,5,6],[7,8,9]], columns=['a', 'b', 'c'])

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

### Selección de columnas.

Para **seleccionar una o varias columnas** se utiliza los `[ ]`.

```
<df>[<cols>]
```

Donde:

* ```<df>``` es un dataframe de *Pandas*.
* ```<cols>``` es un objeto de tipo:
  -  ```str``` o `int` correspondiente al identificador de una columna.
  - `list` para seleccionar varias columnas

**Ejemplo:**

- Identificadores numéricos *int*

In [ ]:
data = pd.DataFrame( ((5, 1, 2), (1, 2, 8)) )
data

   0  1  2
0  5  1  2
1  1  2  8

In [ ]:
# Seleccionar la segunda columna
data[1]

0    1
1    2
Name: 1, dtype: int64

- Identificadores tipo *string*

In [ ]:
data = {'Nombre': ['Juan', 'Ana', 'Jose', 'Tito'],
        'Edad':   [25, 18, 23, 27],
        'Pais':   ['BO', 'CO', 'AR', 'BO']}
estudiantes = pd.DataFrame(data)
estudiantes

  Nombre  Edad Pais
0   Juan    25   BO
1    Ana    18   CO
2   Jose    23   AR
3   Tito    27   BO

In [ ]:
# Seleccionar la columna 'Nombre'
estudiantes['Nombre']

0    Juan
1     Ana
2    Jose
3    Tito
Name: Nombre, dtype: object

In [ ]:
# Seleccionar varias columnas
estudiantes[['Pais', 'Nombre']]

  Pais Nombre
0   BO   Juan
1   CO    Ana
2   AR   Jose
3   BO   Tito

**Nota**: Al seleccionar una columna de un dataframe, lo que se obtiene es una "serie".

In [ ]:
# Verificar el tipo dato nos devuelve, 'pd.Series'
print(type(estudiantes['Nombre']))

<class 'pandas.core.series.Series'>

### Selección de filas
Similar a selección de columnas, excepto que se usa sintaxis de rango

#### indices numéricos.

Permite utilizar una **sintaxis de rango** para seleccionar filas.

```
<df>[<inicio>:<fin>:<pasos>]
```

Donde:

* ```<inicio>``` es un indice numérico `int` correspondiente a la primera fila del rango.
* ```<fin>``` es un indice numérico `int`  correspondiente a la última menos una, fila del rango. (**Es no incluido**)
* ```<pasos>``` un entero que corresponde al tamaño de incrementos/decrementos que se aplicará al rango.

**Ejemplos:**

In [ ]:
data = {'Nombre': ['Juan', 'Ana', 'Jose', 'Tito'],
        'Edad':   [25, 18, 23, 27],
        'Pais':   ['BO', 'CO', 'AR', 'BO']}
estudiantes = pd.DataFrame(data)
estudiantes

  Nombre  Edad Pais
0   Juan    25   BO
1    Ana    18   CO
2   Jose    23   AR
3   Tito    27   BO

In [ ]:
# Seleccionar las filas con indice 1 al 3
estudiantes[1:4:1]

  Nombre  Edad Pais
1    Ana    18   CO
2   Jose    23   AR
3   Tito    27   BO

In [ ]:
# Seleccionar los últimos dos estudiantes
estudiantes[-2:]

  Nombre  Edad Pais
2   Jose    23   AR
3   Tito    27   BO

In [ ]:
# Seleccionar los estudiantes con indice 0, 2, 4, ...
estudiantes[::2]

  Nombre  Edad Pais
0   Juan    25   BO
2   Jose    23   AR

**Nota**: Al seleccionar filas, lo que se obtiene es otro *DataFrame*

In [ ]:
# El tipo de objeto resultante es otro DataFrame
print(type(estudiantes[:1]))

<class 'pandas.core.frame.DataFrame'>

#### Indices tipo string

De manera similar a los indices numéricos, se puede utilizar una sintaxis de rango.

```
<df>[<id_inicio>:<id_fin>]
```

Donde:
* ```<id_inicio>``` es un ```str``` correspondiente al identificador de fila desde donde iniciará el rango.
* ```<id_fin>``` es un objeto ```str``` correspondiente al identificador de fila donde finalizará el rango. (**Es incluido**)

**Ejemplos:**

In [ ]:
data = {'Nombre': ['Juan', 'Ana', 'Jose', 'Tito'],
        'Edad':   [25, 18, 23, 27],
        'Pais':   ['BO', 'CO', 'AR', 'BO']}
estudiantes = pd.DataFrame(data, index=['J25BO', 'A18CO', 'JAR23', 'T27BO'])
estudiantes

      Nombre  Edad Pais
J25BO   Juan    25   BO
A18CO    Ana    18   CO
JAR23   Jose    23   AR
T27BO   Tito    27   BO

In [ ]:
# Recuperar un rango
estudiantes['A18CO':'T27BO']

      Nombre  Edad Pais
A18CO    Ana    18   CO
JAR23   Jose    23   AR
T27BO   Tito    27   BO

### Selección de elementos


Se utiliza la siguiente sintaxis:

```
<df>[<col>][<fila(s)>]
```

- `<col>` es el identificador de columna (solo uno).
- `<fila(s)>` es el identificador de filas (un identificador o un rango).

**Ejemplo:**

In [ ]:
data = {'Nombre': ['Juan', 'Ana', 'Jose', 'Tito'],
        'Edad':   [25, 18, 23, 27],
        'Pais':   ['BO', 'CO', 'AR', 'BO']}
estudiantes = pd.DataFrame(data, index=['J25BO', 'A18CO', 'JAR23', 'T27BO'])
estudiantes

      Nombre  Edad Pais
J25BO   Juan    25   BO
A18CO    Ana    18   CO
JAR23   Jose    23   AR
T27BO   Tito    27   BO

In [ ]:
# Seleccionar un solo elemento
estudiantes['Edad']['JAR23']

np.int64(23)

In [ ]:
# Seleccionar un rango de elemento
estudiantes['Edad']['JAR23':'T27BO']

JAR23    23
T27BO    27
Name: Edad, dtype: int64

In [ ]:
# Las columnas no aceptan rangos, lanzará un ValueError.
#estudiantes['Edad':'Pais']['T27BO']

## Las *series*

Las series de *Pandas* son arreglos de datos de una dimensión

### Creacion de *Series*

La clase `pandas.Series` se utiliza para crear series.

```
pd.Series(<datos>)
```

Donde:

* ```<datos>``` puede ser un objeto de tipo: ```tuple```, ```list```, ```dict``` o ```numpy.ndarray``` de una dimensión.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html

**Ejemplo:**

In [ ]:
# Crear una serie a partir de una lista
pd.Series([12, 4, 32, 41, 33, 28])

0    12
1     4
2    32
3    41
4    33
5    28
dtype: int64

#### Índices en las series.

Al igual que los *Dataframes*, las series soportan el atributo ```index``` para identificar filas. Y cuenta con el atributo `name` para identificar la columna.


```
pd.Series(<datos>, name="<id-col>", index=<id-fila>)
```

* ```<id-col>``` es un ```str``` para identificar a la columna.
* `<id-fila>` es un objeto iterable (p.e. lista) de `str` para identificar cada elemento de la *Serie*.

Si no se estable estos parámetros, los indices **por defecto son números**.

**Ejemplo:**

In [ ]:
pd.Series([12, 4, 32, 41],
          index=['Tito', 'Pepe', 'Mary', 'Luis'], name='Edad')

Tito    12
Pepe     4
Mary    32
Luis    41
Name: Edad, dtype: int64

### Selección de elementos

Se utiliza los `[ ]` para acceder a un elemento.


```
<serie>[<identificador>]
```
Donde:

- `<identificador>` será un `int` o `str` dependiendo del tipo establecido.

**Ejemplos**

In [ ]:
# Ejemplo 1: Serie con indices por defecto
s = pd.Series([12, 24, 32, 41])

# Seleccionar un elemento
s[1]

np.int64(24)

In [ ]:
# Ejemplo 2: Serie con indices tipo string
s = pd.Series([12, 24, 32, 41], name='Edad'
                              , index=['Tito', 'Pepe', 'Mary', 'Luis'])

# Seleccionar la edad de 'Pepe'
s['Pepe']

np.int64(24)

## Conversión de series a dataframes.

El método ```pd.Series.to_frame()``` permite transformar una serie en un dataframe de una columna.

```
<serie>.to_frame()
```

**Ejemplo:**

In [ ]:
pd.Series([12, 24, 32, 41],
            name='Edad',
            index=['Tito', 'Pepe', 'Mary', 'Luis']).to_frame()

      Edad
Tito    12
Pepe    24
Mary    32
Luis    41

## Broadcasting.

Las series y dataframes de *Pandas* son compatibles con el broadcasting de los arreglos de *Numpy*.

**Ejemplo:**

In [ ]:
datos = pd.DataFrame(np.arange(20).reshape(5,4),
                     columns=('col-1', 'col-2', 'col-3', 'col-4'))
datos

   col-1  col-2  col-3  col-4
0      0      1      2      3
1      4      5      6      7
2      8      9     10     11
3     12     13     14     15
4     16     17     18     19

In [ ]:
# Multiplicar por 5 los elementos con indice 2 en adelante
datos[2:] * 5

   col-1  col-2  col-3  col-4
2     40     45     50     55
3     60     65     70     75
4     80     85     90     95

In [ ]:
# Guardar el resultado en el mismo dataframe
datos[2:] = datos[2:] * 5
datos

   col-1  col-2  col-3  col-4
0      0      1      2      3
1      4      5      6      7
2     40     45     50     55
3     60     65     70     75
4     80     85     90     95